### ISSUE TITLE
Donate page self-referential

### ISSUE THREAD

**Issue by coke** [tpf/www.perlfoundation.org#3]
Donate button takes you to the donate page.. but the donate button there also takes you to the donate page. Don't see an obvious link to donate.

**Comment by coke** [comment]
There are 3 donate buttons on the site. the only one with the issue is the one at the bottom of the page. I would just remove it, but there's some text there. Someone should review the text  and incorporate it at the top of the page or remove it if it's unneeded.

**Comment by dwright** [comment]
The "Donate Online" button at the top of the page is correct.    The "Donate" button at the bottom of the page is wrong.     We probably want both buttons to go to the same place.

**Comment by dwright** [comment]
This is done.
